name: Homework 1
on:
  push:
    branches: [ main ]
    paths:
      - 'hw1/**'
  workflow_dispatch:

jobs:
  Tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hw1
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Build
        run: ./gradlew build -x test

      - name: Test
        run: ./gradlew test

      - name: Benchmark
        run: ./gradlew jmh